RED Test: Status is true when .lock is run
Failures:

  1) Diary sets locked status to true when run .unlock
     Failure/Error: subject.lock

     NoMethodError:
       undefined method `lock' for #<Diary:0x00007fe7c197af80 @locked_status=true>
       Did you mean?  unlock
     # ./spec/secret_diary_spec.rb:23:in `block (2 levels) in <top (required)>'

Finished in 0.00454 seconds (files took 0.08767 seconds to load)
4 examples, 1 failure